services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/config"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs"
      - "./config:/etc/traefik/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
    networks:
      - app-wallet-network

  pets-app:
    volumes:
      - ./app:/app:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pets-http.rule=Host(`${DOMAIN_BASE}`)"
      - "traefik.http.routers.pets-http.entrypoints=web"
      - "traefik.http.routers.pets-secure.rule=Host(`${DOMAIN_BASE}`)"
      - "traefik.http.routers.pets-secure.entrypoints=websecure"
      - "traefik.http.routers.pets-secure.tls=true"
      - "traefik.http.services.pets.loadbalancer.server.port=80"
